import { StyleSheet, Dimensions } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#E5E5E5',
        paddingLeft: 10,
        paddingRight: 10,
        paddingTop: -20,
    },
    image: {
        width: Dimensions.get('window').width,
        height: 250,
        marginRight: 5,

    },
    containImage: {
        flexDirection: 'row',
    },
    areaImage: {
        width: Dimensions.get('window').width,
        height: 250,
        borderWidth: 1,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        backgroundColor: '#FFF',
        borderRadius: 5,
        borderColor: '#EFF5FB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        marginBottom: 10,

    },
    inputTitle: {
        width: '100%',
        height: 40,
        padding: 10,
        borderWidth: 0.2,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        backgroundColor: '#FFF',
        borderRadius: 5,
        borderColor: '#EFF5FB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        marginBottom: 10,

    },
    textTitle: {
        fontSize: 15,
        marginBottom: 5,
        fontWeight:'bold'
    },
    inputDesc: {
        width: '100%',
        height: 130,
        padding: 10,
        borderWidth: 0.2,
        borderWidth: 1,
        backgroundColor: '#FFF',
        borderRadius: 5,
        borderColor: '#EFF5FB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        marginBottom: 10,

    },
    selectCategory: {
        width: '100%',
        height: 40,
        padding: 10,
        borderWidth: 0.2,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        backgroundColor: '#FFF',
        borderRadius: 5,
        borderColor: '#EFF5FB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        marginBottom: 10,
    },
    picker: {
        width: '100%',
        height: 40,
        padding: 10,
        borderWidth: 0.2,
        flexDirection: 'column',
        justifyContent: 'center',
        borderWidth: 1,
        backgroundColor: '#FFF',
        borderRadius: 5,
        borderColor: '#EFF5FB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        marginBottom: 10,
    },
    inputCep: {
        width: '98%',
        height: 40,
        fontSize:20,
        fontWeight:'bold',
        padding: 10,
        borderWidth: 0.2,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        backgroundColor: '#FFF',
        borderRadius: 5,
        borderColor: '#EFF5FB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        marginBottom: 10,
    },
    pickerCond: {
        width: '98%',
        height: 40,
        padding: 10,
        borderWidth: 0.2,
        flexDirection: 'column',
        justifyContent: 'center',
        borderWidth: 1,
        backgroundColor: '#FFF',
        borderRadius: 5,
        borderColor: '#EFF5FB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        marginBottom: 10,
    },
    containCondIptu: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center'
    },
    areaCep: {
        width: '50%',
    },
    areaCond: {
        width: '50%',
        marginLeft: 5
    },




});

export default styles