import { StyleSheet, Dimensions } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#E5E5E5',
        paddingLeft: 10,
        paddingRight: 10,
        paddingTop: -20,
    },
    image: {
        width: Dimensions.get('window').width,
        height: 250,
        marginRight: 10,

    },
    containImage: {
        flexDirection: 'row',

    },
    areaImage: {
        width: Dimensions.get('window').width,
        height: 250,
        borderWidth: 1,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        backgroundColor: '#FFF',
        borderRadius: 5,
        borderColor: '#EFF5FB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        marginBottom: 10,
        marginRight: 5,
    },
    inputTitle: {
        width: '100%',
        height: 40,
        padding: 10,
        borderWidth: 0.2,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        backgroundColor: '#FFF',
        borderRadius: 5,
        borderColor: '#EFF5FB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        marginBottom: 10,
    },
    textTitle: {
        fontSize: 15,
        marginBottom: 5,
        fontWeight: 'bold'
    },
    textResCep: {
        textAlign:'center',
        fontSize: 14,
        marginBottom: 5,
        marginTop: -5,
        fontWeight: 'bold',
        color:'#6E6E6E'
    },
    inputDesc: {
        width: '100%',
        height: 130,
        padding: 10,
        borderWidth: 0.2,
        borderWidth: 1,
        backgroundColor: '#FFF',
        borderRadius: 5,
        borderColor: '#EFF5FB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        marginBottom: 10,

    },
    selectCategory: {
        width: '100%',
        height: 40,
        padding: 10,
        borderWidth: 0.2,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        backgroundColor: '#FFF',
        borderRadius: 5,
        borderColor: '#EFF5FB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        marginBottom: 10,
    },
    picker: {
        width: '100%',
        height: 40,
        padding: 10,
        borderWidth: 0.2,
        flexDirection: 'column',
        justifyContent: 'center',
        borderWidth: 1,
        backgroundColor: '#FFF',
        borderRadius: 5,
        borderColor: '#EFF5FB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        marginBottom: 10,
    },
    inputCep: {
        width: '98%',
        height: 40,
        fontSize: 17,
        fontWeight: 'bold',
        padding: 10,
        borderWidth: 0.2,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        backgroundColor: '#FFF',
        borderRadius: 5,
        borderColor: '#EFF5FB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        marginBottom: 10,
    },
    pickerCond: {
        width: '98%',
        height: 40,
        padding: 10,
        borderWidth: 0.2,
        flexDirection: 'column',
        justifyContent: 'center',
        borderWidth: 1,
        backgroundColor: '#FFF',
        borderRadius: 5,
        borderColor: '#EFF5FB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        marginBottom: 10,
    },
    containCepCod: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center'
    },
    areaCep: {
        width: '50%',
    },
    areaCond: {
        width: '50%',
        marginLeft: 5
    },
    submit: {
        width: '100%',
        height: 40,
        padding: 10,
        borderWidth: 0.2,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        backgroundColor: '#FF8000',
        borderRadius: 5,
        borderColor: '#FF8000',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 1,
        shadowRadius: 2,
        elevation: 5,
        marginBottom: 10,
    },
    textSubmit: {
        fontSize: 15,
        marginLeft: 3,
        color: '#fff',
        fontWeight: 'bold'
    }


});

export default styles